"use client";

/* eslint-disable @next/next/no-img-element -- the QR code is a data URL generated by our own API */
import { MessageCircle, Smartphone } from "lucide-react";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";
import { Badge, Button, ErrorText } from "@/components/ui";
import { api } from "@/lib/api-client";
import { formatWhatsApp } from "@/lib/whatsapp";

export type FirmWhatsAppView = {
  status: "disconnected" | "connecting" | "qr" | "connected";
  phone: string | null;
  qr: string | null;
  error: string | null;
  connectedAt: string | null;
  queued?: number;
  mode: "service" | "off";
  available: boolean;
};

/**
 * Admin control for the firm's WhatsApp: link once by scanning a QR code (like
 * WhatsApp Web → Linked devices); every user's messages then go out from it.
 */
export function WhatsAppLink({ initial, canManage }: { initial: FirmWhatsAppView; canManage: boolean }) {
  const router = useRouter();
  const [s, setS] = useState<FirmWhatsAppView>(initial);
  const [busy, setBusy] = useState<"link" | "unlink" | null>(null);
  const [error, setError] = useState<string | null>(null);
  const timer = useRef<NodeJS.Timeout | null>(null);
  const wasConnected = useRef(initial.status === "connected");

  const refresh = useCallback(async () => {
    try {
      const next = await api<FirmWhatsAppView>("/api/whatsapp");
      setS(next);
      if (next.status === "connected" && !wasConnected.current) {
        wasConnected.current = true;
        router.refresh();
      }
    } catch {
      /* transient */
    }
  }, [router]);

  useEffect(() => {
    if (s.status !== "qr" && s.status !== "connecting") return;
    timer.current = setInterval(refresh, 2000);
    return () => {
      if (timer.current) clearInterval(timer.current);
    };
  }, [s.status, refresh]);
  useEffect(() => {
    if (initial.available && (initial.status === "qr" || initial.status === "connecting")) void refresh();
  }, [initial.available, initial.status, refresh]);

  async function link() {
    setBusy("link");
    setError(null);
    try {
      setS(await api<FirmWhatsAppView>("/api/whatsapp", "POST"));
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setBusy(null);
    }
  }
  async function unlink() {
    if (!confirm("Unlink the firm's WhatsApp from the CRM? Messages will open in each user's WhatsApp app instead.")) return;
    setBusy("unlink");
    try {
      await api("/api/whatsapp", "DELETE");
      wasConnected.current = false;
      setS({ ...s, status: "disconnected", phone: null, qr: null, error: null, connectedAt: null });
      router.refresh();
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setBusy(null);
    }
  }

  if (!s.available) {
    return (
      <div className="space-y-2" data-testid="whatsapp-link" data-status="unavailable">
        <p className="flex items-center gap-2 text-sm text-gray-700">
          <Smartphone size={16} className="text-gray-400" /> <Badge>WhatsApp service not configured</Badge>
        </p>
        <p className="text-xs text-gray-500">
          The firm&apos;s WhatsApp is held by a small separate service (<code>whatsapp/server.mjs</code>, run with pm2 as <code>beipoready-crm-whatsapp</code>) so the linked session survives redeploys. On the server: set <code>WHATSAPP_SERVICE_TOKEN</code> in <code>.env</code>, run <code>npm run whatsapp:pm2</code>, then give this deployment <code>WHATSAPP_SERVICE_URL</code> (e.g. <code>http://127.0.0.1:3018</code>, or its public https address when the CRM runs elsewhere) and the same token. Until then, WhatsApp buttons open each user&apos;s WhatsApp app with the message prefilled, and staff alerts use CallMeBot keys.
        </p>
      </div>
    );
  }
  return (
    <div className="space-y-3" data-testid="whatsapp-link" data-status={s.status}>
      <ErrorText>{error ?? (s.status === "disconnected" ? s.error : null)}</ErrorText>
      {s.status === "connected" ? (
        <div className="flex flex-wrap items-center justify-between gap-3">
          <p className="flex items-center gap-2 text-sm text-gray-800">
            <MessageCircle size={16} className="text-emerald-600" />
            <Badge tone="green">Linked</Badge>
            <span>
              {s.phone ? formatWhatsApp(s.phone) : "WhatsApp"} — meeting details and messages from every user go out from this number.
              {s.queued ? ` ${s.queued} message${s.queued === 1 ? "" : "s"} waiting to send.` : ""}
            </span>
          </p>
          {canManage && (
            <Button size="sm" variant="ghost" onClick={unlink} loading={busy === "unlink"}>
              Unlink
            </Button>
          )}
        </div>
      ) : s.status === "qr" && s.qr ? (
        <div className="flex flex-wrap items-start gap-5">
          <img src={s.qr} alt="WhatsApp QR code" width={220} height={220} className="rounded-lg border border-gray-200 bg-white p-1" data-testid="whatsapp-qr" />
          <ol className="list-decimal space-y-1.5 pl-5 text-sm text-gray-700">
            <li>Open WhatsApp on the firm&apos;s phone.</li>
            <li>
              Tap <b>⋮</b> (Android) or <b>Settings</b> (iPhone) → <b>Linked devices</b>.
            </li>
            <li>
              Tap <b>Link a device</b> and scan this code.
            </li>
            <li className="text-xs text-gray-500">The code refreshes by itself; this page updates as soon as the phone links.</li>
          </ol>
        </div>
      ) : s.status === "connecting" ? (
        <p className="flex items-center gap-2 text-sm text-gray-600">
          <span className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-current border-r-transparent" /> {s.phone ? `Reconnecting ${formatWhatsApp(s.phone)}…` : "Contacting WhatsApp…"}
        </p>
      ) : (
        <div className="flex flex-wrap items-center justify-between gap-3">
          <p className="flex items-center gap-2 text-sm text-gray-700">
            <Smartphone size={16} className="text-gray-400" /> <Badge>Not linked</Badge> {canManage ? "Link the firm's WhatsApp so everyone can send from it." : "Ask an administrator to link the firm's WhatsApp under Settings."}
          </p>
          {canManage && (
            <Button size="sm" onClick={link} loading={busy === "link"} data-testid="link-whatsapp">
              <MessageCircle size={14} /> Link WhatsApp
            </Button>
          )}
        </div>
      )}
      <p className="text-xs text-gray-500">
        Works like WhatsApp Web (open-source Baileys client) inside the separate WhatsApp service, so redeploying the CRM never drops the link. Messages are sent one at a time, 3–7 seconds apart. WhatsApp doesn&apos;t officially support third-party linked apps and heavy automated use can get a number banned, so keep it to normal client conversation volumes; for a fully supported route use the WhatsApp Business Cloud API or a provider built on it. Every message sent this way is recorded on the client&apos;s timeline with the sender&apos;s name.
      </p>
    </div>
  );
}
